image: python:3.9

stages:
  - test

test:
  stage: test
  only:
   changes:
    - .gitlab-ci.yml
    - setup.{cfg,py}
    - Makefile
    - openfisca_france_pension/*.py
    - openfisca_france_pension/parameters
  script:
    - pip install -e .[dev]
    - make test

validate_yaml:
  stage: test
  image: curlimages/curl:latest
  variables:
    PARAMETERS_PATH: openfisca_france_pension/parameters
  script:
    - |
      env | curl --data-binary @- --fail-with-body --header "Content-Type: text/plain; charset=utf-8" --max-time 300 --silent https://control-center.tax-benefit.org/api/gitlab/ci

tax-benefit_deploy:
  stage: test
  image: curlimages/curl:latest
  variables:
    PYTHON_PACKAGE: openfisca_france_pension
  script:
    - |
      env | curl --data-binary @- --fail-with-body --header "Content-Type: text/plain; charset=utf-8" --max-time 300 --silent https://control-center.tax-benefit.org/api/gitlab/ci
