name: openfisca-france-pension
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - openfisca::openfisca-core
  - bottleneck >=1.3.2,<=2.0.0
  - numba >=0.54,<1.0.0
  - pandas >=2.0,<3.0
  - pip
  - pip:
    - OpenFisca-Core",
